# Grouping Data & Aggregating Variables
## This script contains the following points;
## 1. Importing Data
## 2. Grouping Data with pandas
    2.1 Grouping Subset Data 
    2.2 Apply Subset Groups Into The Main Data Frame *
    2.3 Creating the Loyalty flag - Aggragating Data for Different Customer Types
    2.4 Basic Product Price Statistics for Customer Loyalty Categories *
    2.5 Spending Categories (above and below average price per product) * 
    2.6 Frequent and Non-Frequent Customers *
## 3. Exporting data *

    * requested tasks

## 1. Importing Data

In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
path = r'C:\Users\senja\OneDrive\Documents\5. Learning\4. Data Analytics Immersion\Instacart Basket Analysis'

In [3]:
path

'C:\\Users\\senja\\OneDrive\\Documents\\5. Learning\\4. Data Analytics Immersion\\Instacart Basket Analysis'

In [4]:
#import updated merged pkl file

ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'updated_merged.pkl'))

In [5]:
#check the columnns

ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders

In [6]:
ords_prods_merge.shape

(32434212, 18)

In [7]:
# create a subset 

df = ords_prods_merge[:1000000]

In [8]:
df.shape

(1000000, 18)

In [9]:
df.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders

## 2. Grouping Data with pandas

### 2.1 Grouping Subset Data

In [10]:
# group the subset data

df.groupby('product_name')

In [11]:
 # group the “department_id" and apply mean values for the “order_number” 
    
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.562844
2                17.518895
3                16.907152
4                17.537934
5                14.894521
6                16.658449
7                17.072954
8                14.942021
9                15.447580
10               18.681852
11               15.352278
12               14.327957
13               16.578690
14               16.666369
15               16.153766
16               17.768070
17               15.602964
18               19.674252
19               16.924344
20               16.292631
21               25.535596

In [1]:
# aggregation without use of the agg() function

df.groupby('department_id')['order_number'].mean()

NameError: name 'df' is not defined

In [13]:
# the use of column name within square brackets 

df.groupby('department_id').order_number.mean()

department_id
1     15.562844
2     17.518895
3     16.907152
4     17.537934
5     14.894521
6     16.658449
7     17.072954
8     14.942021
9     15.447580
10    18.681852
11    15.352278
12    14.327957
13    16.578690
14    16.666369
15    16.153766
16    17.768070
17    15.602964
18    19.674252
19    16.924344
20    16.292631
21    25.535596
Name: order_number, dtype: float64

In [14]:
# performing multiple aggregations

df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.562844   1  99
2                17.518895   1  96
3                16.907152   1  99
4                17.537934   1  99
5                14.894521   1  99
6                16.658449   1  99
7                17.072954   1  99
8                14.942021   1  98
9                15.447580   1  99
10               18.681852   1  99
11               15.352278   1  99
12               14.327957   1  99
13               16.578690   1  99
14               16.666369   1  99
15               16.153766   1  99
16               17.768070   1  99
17               15.602964   1  99
18               19.674252   1  99
19               16.924344   1  99
20               16.292631   1  99
21               25.535596   1  98

### 2.2 Apply Subset Groups Into The Main Data Frame *

In [15]:
# performing multiple aggregations as on subset data

ords_prods_merge.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.457687   1  99
2                17.277920   1  99
3                17.179756   1  99
4                17.811403   1  99
5                15.213779   1  99
6                16.439806   1  99
7                17.225773   1  99
8                15.340520   1  99
9                15.895474   1  99
10               20.197148   1  99
11               16.170828   1  99
12               15.887622   1  99
13               16.583304   1  99
14               16.757377   1  99
15               16.165037   1  99
16               17.663250   1  99
17               15.694469   1  99
18               19.310397   1  99
19               17.177343   1  99
20               16.473447   1  99
21               22.902379   1  99

### Analyze the result. How do the results for the entire dataframe differ from those of the subset. 

#### The mean values are slightly different in many department categories but generally the sample means are quite close to actual means as on the entire data frame. The means are usually greater in the data frame which covers the entire data. This is expected as there are more than 31M  more data rows in the main data frame and therefore data values are expected to be more widely spread out. However, there are few execptions, the mean for department 1, 2, 6, 16, 18 and 21 are greater in the subset data frame. The difference between the department id 2 and 21 can be explained due to the fact that the max order numbers are 96 and 98 in subset whereas they are 99 on the entire data frame. As the subset data frame includes "only" 1M rows, and it is a sample it won't be equal to the entire dataframe, and therefore the sample mean might not be systematically smaller or larger than the entire data frame.

In [16]:
# performing multiple aggregations - means, max and min for prices based on the product name

ords_prods_merge.groupby('product_name').agg({'prices': ['mean', 'min', 'max']})

                                                   prices
                                                     mean   min   max
product_name
#2 Coffee Filters                                    11.0  11.0  11.0
#2 Cone White Coffee Filters                          5.7   5.7   5.7
#2 Mechanical Pencils                                 9.2   9.2   9.2
#4 Natural Brown Coffee Filters                       2.5   2.5   2.5
#NAME?                                                3.6   3.6   3.6
...                                                   ...   ...   ...
with Xylitol Unwrapped Original Flavor 50 Stick...    5.4   5.4   5.4
with Xylitol Unwrapped Spearmint 50 Sticks Suga...    5.2   5.2   5.2
with Xylitol Watermelon Twist 18 Sticks Sugar F...    3.5   3.5   3.5
with a Splash of Mango Coconut Water                  2.6   2.6   2.6
with a Splash of Pineapple Coconut Water              4.2   4.2   4.2

[49661 rows x 3 columns]

In [17]:
# performing multiple aggregations - mean for days based on the product name (min and max are known)

ords_prods_merge.groupby('product_name').agg({'orders_day_of_week': ['mean']})

                                                   orders_day_of_week
                                                                 mean
product_name
#2 Coffee Filters                                            2.696268
#2 Cone White Coffee Filters                                 3.384615
#2 Mechanical Pencils                                        2.875000
#4 Natural Brown Coffee Filters                              2.755187
#NAME?                                                       2.724138
...                                                               ...
with Xylitol Unwrapped Original Flavor 50 Stick...           3.000000
with Xylitol Unwrapped Spearmint 50 Sticks Suga...           3.000000
with Xylitol Watermelon Twist 18 Sticks Sugar F...           2.867647
with a Splash of Mango Coconut Water                         3.260870
with a Splash of Pineapple Coconut Water                     3.037736

[49661 rows x 1 columns]

### 2.3 Creating the Loyalty flag -  Aggregating Data for Different Customer Types

In [18]:
# establish flag criteria - create “max_order” column, group “user_id” column, generate maximum orders on “order_number”

ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [19]:
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders,3

In [20]:
# check the data 

ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,21

In [21]:
pd.options.display.max_rows = None

In [22]:
ords_prods_merge.head(100)

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range,max_order
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,3.0,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,32
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,20.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,32
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,6.0,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,5
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,0.0,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,3
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,9.0,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders,3
5,1,Chocolate Sandwich Cookies,61,19,5.8,1701441,777,16,1,7,26.0,7,0,both,Mid-range product,Regularly busy,Busiest days,Average Orders,26
6,1,Chocolate Sandwich Cookies,61,19,5.8,1871483,825,3,2,14,30.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,9
7,1,Chocolate Sandwich Cookies,61,19,5.8,1290456,910,12,3,10,30.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,12
8,1,Chocolate Sandwich Cookies,61,19,5.8,369558,1052,10,1,20,19.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average Orders,20
9,1,Chocolate Sandwich Cookies,61,19,5.8,589712,1052,15,1,12,15.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders,20
10,1,Chocolate Sandwich Cookies,61,19,5.8,1798115,1379,1,5,11,0.0,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,10
11,1,Chocolate Sandwich Cookies,61,19,5.8,497193,1480,36,3,13,7.0,1,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,43
12,1,Chocolate Sandwich Cookies,61,19,5.8,1727826,1480,38,4,13,7.0,3,1,both,Mid-range product,Least busy,Slowest days,Most Orders,43
13,1,Chocolate Sandwich Cookies,61,19,5.8,2694698,1480,39,2,12,12.0,4,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,43
14,1,Chocolate Sandwich Cookies,61,19,5.8,3171753,1494,6,3,10,2.0,8,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,13
15,1,Chocolate Sandwich Cookies,61,19,5.8,186761,1494,7,2,8,6.0,18,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,13
16,1,Chocolate Sandwich Cookies,61,19,5.8,317121,1494,9,5,8,10.0,12,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,13
17,1,Chocolate Sandwich Cookies,61,19,5.8,200390,1540,4,2,0,7.0,10,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest Orders,28
18,1,Chocolate Sandwich Cookies,61,19,5.8,374436,1540,5,1,21,6.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Average Orders,28
19,1,Chocolate Sandwich Cookies,61,19,5.8,2920553,1540,6,1,0,14.0,9,1,both,Mid-range product,Regularly busy,Busiest days,Fewest Orders,28
20,1,Chocolate Sandwich Cookies,61,19,5.8,2813049,1540,7,2,2,8.0,7,1,both,Mid-range product,Regularly busy,Regularly busy,Fewest Orders,28
21,1,Chocolate Sandwich Cookies,61,19,5.8,2365998,1540,8,1,23,6.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Fewest Orders,28
22,1,Chocolate Sandwich Cookies,61,19,5.8,1604797,1540,9,1,3,28.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Fewest Orders,28
23,1,Chocolate Sandwich Cookies,61,19,5.8,2799665,1540,14,1,14,7.0,10,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders,28
24,1,Chocolate Sandwich Cookies,61,19,5.8,2228851,1540,15,1,14,7.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders,28
25,1,Chocolate Sandwich Cookies,61,19,5.8,2337422,1540,18,0,21,0.0,5,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
26,1,Chocolate Sandwich Cookies,61,19,5.8,2699008,1540,19,0,22,7.0,11,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
27,1,Chocolate Sandwich Cookies,61,19,5.8,1914830,1540,20,0,22,7.0,11,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
28,1,Chocolate Sandwich Cookies,61,19,5.8,783503,1540,21,0,20,7.0,5,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
29,1,Chocolate Sandwich Cookies,61,19,5.8,2500516,1540,22,0,22,7.0,15,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
30,1,Chocolate Sandwich Cookies,61,19,5.8,716845,1540,24,4,22,3.0,4,1,both,Mid-range product,Least busy,Slowest days,Average Orders,28
31,1,Chocolate Sandwich Cookies,61,19,5.8,1955535,1540,25,6,19,16.0,6,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,28
32,1,Chocolate Sandwich Cookies,61,19,5.8,1424793,1540,27,1,1,5.0,1,1,both,Mid-range product,Regularly busy,Busiest days,Fewest Orders,28
33,1,Chocolate Sandwich Cookies,61,19,5.8,749498,1540,28,0,21,6.0,1,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,28
34,1,Chocolate Sandwich Cookies,61,19,5.8,2434812,1598,1,2,12,0.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,4
35,1,Chocolate Sandwich Cookies,61,19,5.8,1531889,1598,2,2,10,21.0,2,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,4
36,1,Chocolate Sandwich Cookies,61,19,5.8,726947,1598,3,4,17,2.0,3,1,both,Mid-range product,Least busy,Slowest days,Average Orders,4
37,1,Chocolate Sandwich Cookies,61,19,5.8,627615,1647,1,1,9,0.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Average Orders,10
38,1,Chocolate Sandwich Cookies,61,19,5.8,2507439,1647,4,0,13,18.0,6,1,both,Mid-range product,Busiest day,Busiest days,Most Orders,10
39,1,Chocolate Sandwich Cookies,61,19,5.8,1152609,1647,6,1,9,8.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Average Orders,10
40,1,Chocolate Sandwich Cookies,61,19,5.8,1048339,1647,8,0,17,30.0,10,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,10
41,1,Chocolate Sandwich Cookies,61,19,5.8,2818381,1647,9,4,15,25.0,1,1,both,Mid-range product,Least busy,Slowest days,Most Orders,10
42,1,Chocolate Sandwich Cookies,61,19,5.8,2722928,2833,1,0,14,0.0,12,0,both,Mid-range product,Busiest day,Busiest days,Most Orders,10
43,1,Chocolate Sandwich Cookies,61,19,5.8,1482338,2850,7,1,16,9.0,10,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,23
44,1,Chocolate Sandwich Cookies,61,19,5.8,2311344,2857,24,1,8,10.0,5,0,both,Mid-range product,Regularly busy,Busiest days,Average Orders,25
45,1,Chocolate Sandwich Cookies,61,19,5.8,812943,3010,5,3,10,7.0,11,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,13
46,1,Chocolate Sandwich Cookies,61,19,5.8,256839,3029,1,2,20,0.0,8,0,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,5
47,1,Chocolate Sandwich Cookies,61,19,5.8,2192488,3395,4,2,10,30.0,7,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,6
48,1,Chocolate Sandwich Cookies,61,19,5.8,207661,3904,1,1,14,0.0,2,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,3
49,1,Chocolate Sandwich Cookies,61,19,5.8,1394659,4006,2,1,10,7.0,8,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,42
50,1,Chocolate Sandwich Cookies,61,19,5.8,2353526,4006,3,1,10,7.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders,42
51,1,Chocolate Sandwich Cookies,61,19,5.8,2269226,4006,5,3,13,7.0,6,1,both,Mid-range product,Regularly busy,Slowest days,Most Orders,42
52,1,Chocolate Sandwich Cookies,61,19,5.8,367316,4006,9,2,11,5.0,3,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,42
53,1,Chocolate Sandwich Cookies,61,19,5.8,1448367,4006,12,1,11,4.0,2,1,both,Mid-range product,Regularly busy,Busiest days,Most Orders,42
54,1,Chocolate Sandwich Cookies,61,19,5.8,19989,4122,11,2,7,8.0,1,0,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,40
55,1,Chocolate Sandwich Cookies,61,19,5.8,2735922,4141,2,0,8,30.0,2,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,9
56,1,Chocolate Sandwich Cookies,61,19,5.8,2469422,4343,1,1,16,0.0,9,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,4
57,1,Chocolate Sandwich Cookies,61,19,5.8,3185558,4553,3,5,16,29.0,1,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,4
58,1,Chocolate Sandwich Cookies,61,19,5.8,350540,4845,6,0,13,12.0,7,0,both,Mid-range product,Busiest day,Busiest days,Most Orders,14
59,1,Chocolate Sandwich Cookies,61,19,5.8,513100,6866,1,4,15,0.0,11,0,both,Mid-range product,Least busy,Slowest days,Most Orders,6
60,1,Chocolate Sandwich Cookies,61,19,5.8,2081405,7275,5,2,23,4.0,6,0,both,Mid-range product,Regularly busy,Regularly busy,Fewest Orders,8
61,1,Chocolate Sandwich Cookies,61,19,5.8,2209807,7669,3,3,15,5.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,21
62,1,Chocolate Sandwich Cookies,61,19,5.8,921798,7669,4,1,17,5.0,6,1,both,Mid-range product,Regularly busy,Busiest days,Average Orders,21
63,1,Chocolate Sandwich Cookies,61,19,5.8,2540226,7669,20,1,8,13.0,3,1,both,Mid-range product,Regularly busy,Busiest days,Average Orders,21
64,1,Chocolate Sandwich Cookies,61,19,5.8,2265792,7981,9,2,15,10.0,2,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,31
65,1,Chocolate Sandwich Cookies,61,19,5.8,3357714,7981,13,0,23,6.0,1,1,both,Mid-range product,Busiest day,Busiest days,Fewest Orders,31
66,1,Chocolate Sandwich Cookies,61,19,5.8,1186573,7981,14,2,23,9.0,1,1,both,Mid-range product,Regularly busy,Regularly busy,Fewest Orders,31
67,1,Chocolate Sandwich Cookies,61,19,5.8,3209740,7981,24,2,13,6.0,2,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,31
68,1,Chocolate Sandwich Cookies,61,19,5.8,138748,7981,30,3,16,8.0,2,1,both,Mid-range product,Regularly busy,Slowest days,Most Orders,31
69,1,Chocolate Sandwich Cookies,61,19,5.8,2027157,8703,34,4,13,1.0,13,0,both,Mid-range product,Least busy,Slowest days,Most Orders,99
70,1,Chocolate Sandwich Cookies,61,19,5.8,3052954,8723,4,3,10,7.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,36
71,1,Chocolate Sandwich Cookies,61,19,5.8,1486756,8735,8,4,11,21.0,2,0,both,Mid-range product,Least busy,Slowest days,Most Orders,9
72,1,Chocolate Sandwich Cookies,61,19,5.8,632514,9293,2,0,12,30.0,2,0,both,Mid-range product,Busiest day,Busiest days,Most Orders,5
73,1,Chocolate Sandwich Cookies,61,19,5.8,1253470,9293,3,3,13,30.0,1,1,both,Mid-range product,Regularly busy,Slowest days,Most Orders,5
74,1,Chocolate Sandwich Cookies,61,19,5.8,837303,9467,1,0,17,0.0,11,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,5
75,1,Chocolate Sandwich Cookies,61,19,5.8,2734881,9694,2,0,17,30.0,3,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,23
76,1,Chocolate Sandwich Cookies,61,19,5.8,2164394,9694,4,4,18,8.0,2,1,both,Mid-range product,Least busy,Slowest days,Average Orders,23
77,1,Chocolate Sandwich Cookies,61,19,5.8,3354551,9694,5,4,15,7.0,1,1,both,Mid-range product,Least busy,Slowest days,Most Orders,23
78,1,Chocolate Sandwich Cookies,61,19,5.8,1381165,9694,6,4,21,14.0,2,1,both,Mid-range product,Least busy,Slowest days,Average Orders,23
79,1,Chocolate Sandwich Cookies,61,19,5.8,2809438,9694,7,4,18,28.0,1,1,both,Mid-range product,Least busy,Slowest days,Average Orders,23
80,1,Chocolate Sandwich Cookies,61,19,5.8,425352,9694,10,4,7,16.0,4,1,both,Mid-range product,Least busy,Slowest days,Average Orders,23
81,1,Chocolate Sandwich Cookies,61,19,5.8,2453441,9694,14,4,22,1.0,1,1,both,Mid-range product,Least busy,Slowest days,Average Orders,23
82,1,Chocolate Sandwich Cookies,61,19,5.8,1189695,9694,15,4,16,14.0,1,1,both,Mid-range product,Least busy,Slowest days,Most Orders,23
83,1,Chocolate Sandwich Cookies,61,19,5.8,1759231,9694,16,4,15,7.0,2,1,both,Mid-range product,Least busy,Slowest days,Most Orders,23
84,1,Chocolate Sandwich Cookies,61,19,5.8,482648,9694,20,4,13,8.0,1,1,both,Mid-range product,Least busy,Slowest days,Most Orders,23
85,1,Chocolate Sandwich Cookies,61,19,5.8,2201348,9694,22,4,14,16.0,7,1,both,Mid-range product,Least busy,Slowest days,Most Orders,23
86,1,Chocolate Sandwich Cookies,61,19,5.8,3351592,9848,17,4,18,8.0,16,0,both,Mid-range product,Least busy,Slowest days,Average Orders,23
87,1,Chocolate Sandwich Cookies,61,19,5.8,2164672,10113,6,4,18,14.0,5,0,both,Mid-range product,Least busy,Slowest days,Average Orders,11
88,1,Chocolate Sandwich Cookies,61,19,5.8,1526735,10315,1,0,16,0.0,2,0,both,Mid-range product,Busiest day,Busiest days,Most Orders,5
89,1,Chocolate Sandwich Cookies,61,19,5.8,2057892,10479,22,1,16,8.0,8,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,22
90,1,Chocolate Sandwich Cookies,61,19,5.8,356685,10708,4,2,14,14.0,15,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,21
91,1,Chocolate Sandwich Cookies,61,19,5.8,1592736,10708,8,2,14,14.0,9,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,21
92,1,Chocolate Sandwich Cookies,61,19,5.8,3125810,10789,10,0,21,10.0,1,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,36
93,1,Chocolate Sandwich Cookies,61,19,5.8,846661,10789,11,0,19,14.0,4,1,both,Mid-range product,Busiest day,Busiest days,Average Orders,36
94,1,Chocolate Sandwich Cookies,61,19,5.8,2363761,10789,16,2,16,4.0,2,1,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,36
95,1,Chocolate Sandwich Cookies,61,19,5.8,602103,10831,8,3,11,23.0,5,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,10
96,1,Chocolate Sandwich Cookies,61,19,5.8,49629,11119,18,1,14,30.0,1,0,both,Mid-range product,Regularly busy,Busiest days,Most Orders,23
97,1,Chocolate Sandwich Cookies,61,19,5.8,317888,11186,13,5,16,2.0,8,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,26
98,1,Chocolate Sandwich Cookies,61,19,5.8,682486,11243,16,3,13,0.0,2,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,43
99,1,Chocolate Sandwich Cookies,61,19,5.8,2861386,11448,10,2,15,3.0,6,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,21

In [23]:
# deriving columns with loc()

ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [24]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [25]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [26]:
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15891077
Loyal customer      10293737
New customer         6249398
Name: loyalty_flag, dtype: int64

In [27]:
# check the multiple columns

ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0       138  Regular customer            28
1       138  Regular customer            30
2       709      New customer             2
3       764      New customer             1
4       764      New customer             3
5       777  Regular customer            16
6       825      New customer             3
7       910  Regular customer            12
8      1052  Regular customer            10
9      1052  Regular customer            15
10     1379      New customer             1
11     1480    Loyal customer            36
12     1480    Loyal customer            38
13     1480    Loyal customer            39
14     1494  Regular customer             6
15     1494  Regular customer             7
16     1494  Regular customer             9
17     1540  Regular customer             4
18     1540  Regular customer             5
19     1540  Regular customer             6
20     1540  Regular customer             7
21     1540  Regular customer             8
22     1540  Regular customer             9
23     1540  Regular customer            14
24     1540  Regular customer            15
25     1540  Regular customer            18
26     1540  Regular customer            19
27     1540  Regular customer            20
28     1540  Regular customer            21
29     1540  Regular customer            22
30     1540  Regular customer            24
31     1540  Regular customer            25
32     1540  Regular customer            27
33     1540  Regular customer            28
34     1598      New customer             1
35     1598      New customer             2
36     1598      New customer             3
37     1647      New customer             1
38     1647      New customer             4
39     1647      New customer             6
40     1647      New customer             8
41     1647      New customer             9
42     2833      New customer             1
43     2850  Regular customer             7
44     2857  Regular customer            24
45     3010  Regular customer             5
46     3029      New customer             1
47     3395      New customer             4
48     3904      New customer             1
49     4006    Loyal customer             2
50     4006    Loyal customer             3
51     4006    Loyal customer             5
52     4006    Loyal customer             9
53     4006    Loyal customer            12
54     4122  Regular customer            11
55     4141      New customer             2
56     4343      New customer             1
57     4553      New customer             3
58     4845  Regular customer             6
59     6866      New customer             1

### 2.4 Basic Product Price Statistics for Customer Loyalty Categories *

#### Check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [28]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.388747  1.0  99999.0
New customer      13.294370  1.0  99999.0
Regular customer  12.496203  1.0  99999.0

### 2.5 Spending Categories (above and below average price per product) *

#### Create a spending flag for each user based on the average price across all their orders using the following criteria: If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.” If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [29]:
# establish spending flag criteria - create mean column, group “user_id” column, generate mean for “prices”

ords_prods_merge['mean_price'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [30]:
# check the data 

ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,add_to_cart_order,reordered,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range,max_order,loyalty_flag,mean_price
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,5,0,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,32,Regular customer,6.935811
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,1,1,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,32,Regular customer,6.935811
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,20,0,both,Mid-range product,Busiest day,Busiest days,Average Orders,5,New customer,7.930208
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,10,0,both,Mid-range product,Regularly busy,Slowest days,Most Orders,3,New customer,4.972414
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,11,1,both,Mid-range product,Least busy,Slowest days,Average Orders,3,New customer,4.972414

In [31]:
# deriving columns with loc()

ords_prods_merge.loc[ords_prods_merge['mean_price'] >= 10, 'Spender_flag'] = 'High spender'

In [32]:
ords_prods_merge.loc[ords_prods_merge['mean_price'] < 10, 'Spender_flag'] = 'Low spender'

In [33]:
ords_prods_merge['Spender_flag'].value_counts(dropna = False)

Low spender     31798850
High spender      635362
Name: Spender_flag, dtype: int64

### 2.6 Frequent and Non-Frequent Customers * 

#### To determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows: If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.” If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer." If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [34]:
ords_prods_merge.columns

Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'prices',
       'order_id', 'user_id', 'order_number', 'orders_day_of_week',
       'order_hour_of_day', 'days_since_prior_order', 'add_to_cart_order',
       'reordered', '_merge', 'price_range_loc', 'Busiest day', 'Busiest days',
       'busiest_period_of_day_range', 'max_order', 'loyalty_flag',
       'mean_price', 'Spender_flag'],
      dtype='object')

In [35]:
# establish order frequency flag criteria - create median column for order frequency, group “user_id” column, generate median for “prices”

ords_prods_merge['median_order_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [36]:
ords_prods_merge.head()

,product_id,product_name,aisle_id,department_id,prices,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,...,_merge,price_range_loc,Busiest day,Busiest days,busiest_period_of_day_range,max_order,loyalty_flag,mean_price,Spender_flag,median_order_frequency
0,1,Chocolate Sandwich Cookies,61,19,5.8,3139998,138,28,6,11,...,both,Mid-range product,Regularly busy,Regularly busy,Most Orders,32,Regular customer,6.935811,Low spender,8.0
1,1,Chocolate Sandwich Cookies,61,19,5.8,1977647,138,30,6,17,...,both,Mid-range product,Regularly busy,Regularly busy,Average Orders,32,Regular customer,6.935811,Low spender,8.0
2,1,Chocolate Sandwich Cookies,61,19,5.8,389851,709,2,0,21,...,both,Mid-range product,Busiest day,Busiest days,Average Orders,5,New customer,7.930208,Low spender,6.0
3,1,Chocolate Sandwich Cookies,61,19,5.8,652770,764,1,3,13,...,both,Mid-range product,Regularly busy,Slowest days,Most Orders,3,New customer,4.972414,Low spender,9.0
4,1,Chocolate Sandwich Cookies,61,19,5.8,1813452,764,3,4,17,...,both,Mid-range product,Least busy,Slowest days,Average Orders,3,New customer,4.972414,Low spender,9.0

In [37]:
# deriving columns with loc()

ords_prods_merge.loc[ords_prods_merge['median_order_frequency'] > 20, 'Frequency_flag'] = 'Non-frequent customer'

In [38]:
ords_prods_merge.loc[(ords_prods_merge['median_order_frequency'] <= 20) & (ords_prods_merge['median_order_frequency'] > 10), 'Frequency_flag'] = 'Regular customer'

In [39]:
ords_prods_merge.loc[ords_prods_merge['median_order_frequency'] <= 10, 'Frequency_flag'] = 'Frequent customer'

In [40]:
ords_prods_merge['Frequency_flag'].value_counts(dropna = False)

Frequent customer        22814871
Regular customer          6929354
Non-frequent customer     2689987
Name: Frequency_flag, dtype: int64

## 3. Exporting data *

In [41]:
ords_prods_merge.to_pickle(os.path.join(path, '02 Data','Prepared Data', 'grouped_merged.pkl'))